import type { NextPage } from "next";
import Head from "next/head";
import FadeIn from "react-fade-in";
import { AboutMe } from "../components/AboutMe";
import { Contact } from "../components/Contact";
import { MainHeader } from "../components/MainHeader";

const Home: NextPage = () => {
  return (
    <div className="bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FadeIn>
        <MainHeader />
        <AboutMe />
        <Contact />
      </FadeIn>
    </div>
  );
};

export default Home;
